### ISSUE TITLE
switch to #if __has_include

### ISSUE THREAD

**Issue by orta** [dblock/ios-snapshot-test-case-expecta#17]
`#if __has_include(<FacebookSDK/FacebookSDK.h>)`

CocoaPods will be dropping support for he old `COCOAPODS_POD_AVAILABLE` defines.

**Comment by orta** [comment]
Looks like this is happening

**Comment by gregcotten** [comment]
Probably should mention this somewhere other than a closed issue.

**Comment by orta** [comment]
This is for a library, not CocoaPods. It's mentioned in a CocoaPods blog post, and the CHANGELOG for the release.

**Comment by gregcotten** [comment]
Wow - not sure how I ended up here! Sorry about that!
