### ISSUE TITLE
Travis-CI: remove update to XCTool 0.1.14 

### ISSUE THREAD

**Issue by dblock** [dblock/ios-snapshot-test-case-expecta#3]
Remove https://github.com/dblock/ios-snapshot-test-case-expecta/blob/master/.travis.yml#L5 when Travis upgrades to 0.1.14. The 0.1.13 version doesn't run Specta tests, see https://github.com/facebook/xctool/issues/202.

**Comment by ealeksandrov** [comment]
This issue is no more relevant, since current [.travis.yml](https://github.com/dblock/ios-snapshot-test-case-expecta/blob/master/.travis.yml) uses just `xcodebuild` + `xcpretty `

**Comment by dblock** [comment]
Right.
