### ISSUE TITLE
Missed commits in 1.3.3 version

### ISSUE THREAD

**Issue by imaks** [dblock/ios-snapshot-test-case-expecta#30]
Looks like some commits from master branch somehow are not included in 1.3.3 version from CocoaPods, https://github.com/dblock/ios-snapshot-test-case-expecta/compare/1.3.3...master

**Comment by orta** [comment]
![screen shot 2015-06-16 at 06 40 12](https://cloud.githubusercontent.com/assets/49038/8181263/92371c46-13f2-11e5-9696-5ea231ec84e5.png)

:+1:
