### ISSUE TITLE
Bump FBSnapshotTestCase to 2.0.3

### ISSUE THREAD

**Issue by johnboiles** [dblock/ios-snapshot-test-case-expecta#32]
2.0.3 comes with support for rendering views that use UIAppearance (via `usesDrawViewHierarchyInRect `) which is a pretty huge feature.

The only bummer about 2.x.x is that it changes the way `FB_REFERENCE_IMAGE_DIR` is loaded. With 2.x.x, `FB_REFERENCE_IMAGE_DIR` is an environment variable, instead of a preprocessor definition. This makes an update to 2.x.x potentially a breaking change. This, however, probably won't affect users who are using Expecta+Snapshots's ability to automatically detect the reference image directory.

Because it's potentially a breaking change, maybe the Expecta+Snapshots version gets bumped to 2.0.0 as well.

I'll give this a try and report back any issues I encounter.

**Comment by orta** [comment]
I'm not at a computer, but I think we might be ignoring the `FB_REFERENCE_IMAGE_DIR`.

**Comment by johnboiles** [comment]
@orta looks like you're right. `FB_REFERENCE_IMAGE_DIR` doesn't get taken into account. At least that lessens the intensity of this change!

One issue I'm looking at is how to pass `usesDrawViewHierarchyInRect` forward. I suppose I'll define a new matcher that accepts `usesDrawViewHierarchyInRect` as a parameter.

**Comment by orta** [comment]
This sounds good to me :+1:

**Comment by johnboiles** [comment]
@orta duplicating all the `record` and `haveValidSnapshot` matchers just for this single parameter didn't sit quite right with me. I instead created a category on the `Expecta` object (from [ExpectaObject.h](https://github.com/specta/expecta/blob/c52e84681323ad42a47e6e96fd6debb577a26cc1/Expecta/ExpectaObject.h)) that has the method `setUsesDrawViewHierarchyInRect:`.

This is similar to how Expecta handles setting timeouts for asynchronous tests, so I think it's a little more Expecta-like.

PR coming shortly!

**Comment by orta** [comment]
Cool!

**Comment by johnboiles** [comment]
PR submitted!

**Comment by orta** [comment]
This is in
