### ISSUE TITLE
Figuring out the tests folder should search closest folders first?

### ISSUE THREAD

**Issue by marcelofabri** [dblock/ios-snapshot-test-case-expecta#39]
The code for searching the reference images folder searches the path starts from `/`: https://github.com/dblock/ios-snapshot-test-case-expecta/blob/master/EXPMatchers%2BFBSnapshotTest.m#L83

This could be dangerous since we shouldn't really make any guarantees about the whole directory structure. IMO, we should search using `[pathComponents reverseObjectEnumerator]`. However, this might break existing projects 🙈 

One could use `setGlobalReferenceImageDir` to avoid this, but having to do it on every test file seems not practical.

**Comment by dblock** [comment]
You should attempt a PR and we can discuss the ramifications. Maybe add a new UPGRADING document.
