### ISSUE TITLE
Removing Specta from dependencies

### ISSUE THREAD

**Issue by aniastrzezek** [dblock/ios-snapshot-test-case-expecta#41]
I'm using a forked version of Specta repository ([Taptera/specta](https://github.com/Taptera/specta)). Putting Specta in `ios-snapshot-test-case-expecta` podspec file results in `target has frameworks with conflicting names: Specta.` error.

As this project is a FBSnapshots extension for Expecta there is no need to add Specta to it.

**Comment by orta** [comment]
It uses Specta to generate test case names, CocoaPods will resolve that version of Specta to your fork fine, what does your podfile look like? ( Also why fork, I don't see anything unique to your Specta fork? )

**Comment by aniastrzezek** [comment]
In the fork I use there is an additional block called `action` which is executed between `beforeEach` and `it` - I like to use it as it allows to extract the part of code that you're testing in each `describe` \ `context` block from configuration & preparation which is handled in `beforeEach`.

My Podfile:

```
platform :ios, '9.0'

use_frameworks!

source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/Taptera/cocoapods-specs'

target 'ProjectName' do

target 'ProjectNameTests' do
    inherit! :search_paths

    pod 'Specta-Taptera'
    pod 'Expecta+Snapshots'
end
end
```

After running `pod install` I get:
```
Downloading dependencies
Using Expecta (1.0.5)
Using Expecta+Snapshots (3.0.0)
Using FBSnapshotTestCase (2.1.1)
Using Specta (1.0.5)
Installing Specta-Taptera (1.0.5)
[!] The 'Pods-CallrestoBusinessTests' target has frameworks with conflicting names: Specta.
```

**Comment by orta** [comment]
Hrm, ideally you should be using `pod "Specta", :git => "https://github.com/Taptera/specta.git"` here, by re-naming Specta you're gonna get into problems like this, as we don't have real namespacing in objc/swift. 

I'm not removing the Specta dep ( in CP 1.0 you cannot do faux weak-linking anymore ) as the features it offers are basically 90% of my use case for the library.

**Comment by aniastrzezek** [comment]
Ok, thank you!
