### ISSUE TITLE
Random failures of tests on Expecta prerequisite block

### ISSUE THREAD

**Issue by dragvs** [dblock/ios-snapshot-test-case-expecta#42]
There are implicit ptr to BOOL casts in prerequisite blocks of FBSnapshotTest matcher. There is some chance that implicit BOOL cast will return NO for non nil pointers - in case of zero values of 8 lower bits of a pointer.

**Comment by dblock** [comment]
Would love a spec + fix, thanks.

**Comment by dragvs** [comment]
Looks like it depends on the tests executing runtime/architecture. I use pre x86-64 simulator (iPad Retina actually) to run my tests within a CI process so BOOL is defined as a signed char. Don't know if it's a valid requirement to run on such simulator devices. Spec for this is going to be a little bit scary with manual malloc/free to get the properly aligned UIView ptr.

**Comment by orta** [comment]
Thanks! closed by #43
