### ISSUE TITLE
New release needed.

### ISSUE THREAD

**Issue by dominikoledzki** [dblock/ios-snapshot-test-case-expecta#44]
There was no release since May 2016 and meanwhile some useful functionality appeared, for example this commit: https://github.com/dblock/ios-snapshot-test-case-expecta/commit/9278c29622a966cf7f59c937644d7420bb9a5b9d

Could you please publish the next release?

**Comment by orta** [comment]
This is done 👍  
![screen shot 2017-02-07 at 2 59 31 pm](https://cloud.githubusercontent.com/assets/49038/22709160/d28a3470-ed46-11e6-8ed1-7c6bc0c2e972.png)
